name = "SimpleImageView"
uuid = "c6ce2cd2-2c2a-488c-bfa1-710b1b6847e9"
authors = ["Felix Wechsler (roflmaostc) <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"

[compat]
julia = "1"
Colors = "0.12"
ImageShow = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
